apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
  labels:
    app: recipes
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe
  template:
    metadata:
      labels:
        app: recipe
        env: dev
    spec:
      containers:
        - name: recipe
          image: cmbrose.azurecr.io/recipes
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: RAILS_ENV
              value: production
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: secret-key-base
