default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_bin

development:
  <<: *default
  database: recipes
  username: root
  password:

production:
  <<: *default
  host: recipes-dev.mysql.database.azure.com
  port: 3306
  database: recipes
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  sslcapath: <%= ENV['DB_SSL_CA_PATH'] %>
